// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB23hBrH9fpfLmJMvVjFPQLXUJUtIye2YY',
    appId: '1:360691057017:web:1577a6fcf3cc0e031dafa8',
    messagingSenderId: '360691057017',
    projectId: 'fittin-test-task',
    authDomain: 'fittin-test-task.firebaseapp.com',
    storageBucket: 'fittin-test-task.appspot.com',
    measurementId: 'G-PSG7FEHVT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKnutAOVvBkpktpiKYqubWX4g0DYmu3NE',
    appId: '1:360691057017:android:14db426373eb4d7e1dafa8',
    messagingSenderId: '360691057017',
    projectId: 'fittin-test-task',
    storageBucket: 'fittin-test-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMju_xdfHvDGgdBE0FwCECaidir4H8zjU',
    appId: '1:360691057017:ios:e9391002a87d90d71dafa8',
    messagingSenderId: '360691057017',
    projectId: 'fittin-test-task',
    storageBucket: 'fittin-test-task.appspot.com',
    iosClientId: '360691057017-gagmna8kcf3cpd5nnigfirr39v2dbeff.apps.googleusercontent.com',
    iosBundleId: 'com.example.testTask',
  );
}
